Some tweaks
FeikoJoosten/openrgb_ha pull request #1
Opened 2021-08-16 11:51 UTC by koying

Thanks for the PR!

Some tweaks:
- Do not break unique_id from previous version
- Add device id to name, when, e.g., you have twice the same DIMM ;)
- I added a config option for leds, rather than adding them disabled

2021-08-16 18:35 UTC, FeikoJoosten requested changes
See comments :D

2021-08-16 18:35 UTC, FeikoJoosten commented on custom_components/openrgb/light.py
> +            dev_unique_id = f"openrgb.{orgb_object_id(dev_id)}"
@koying I do understand why you'd want to keep the backwards compatibility for the unique id generation. However the [homeassistant docs](https://developers.home-assistant.io/docs/entity_registry_index/) state the following

> An entity is looked up in the registry based on a combination of the platform type (e.g., light), and the integration name (domain) (e.g. hue) and the unique ID of the entity. Entities should not include the domain (e.g., your_integration) and platform type (e.g., light) in their Unique ID as the system already accounts for these identifiers.

Which is why I'm suggesting to remove the `openrgb.` part from the unique id generation

2021-08-16 18:35 UTC, FeikoJoosten commented on custom_components/openrgb/__init__.py
> +            if CONF_ADD_LEDS in config and config[CONF_ADD_LEDS]:
@koying if you do want to keep the backwards compatibility for unique id generation. You should add support for it after line 167.

2021-08-16 19:58 UTC, koying commented on custom_components/openrgb/light.py
> +            dev_unique_id = f"openrgb.{orgb_object_id(dev_id)}"
Yeah, make sense.
Oh, well...  I don't care personally, but I wanted to avoid impacting all users...

I'll remove those  tomorrow

2021-08-16 19:59 UTC, FeikoJoosten commented on custom_components/openrgb/light.py
> +            dev_unique_id = f"openrgb.{orgb_object_id(dev_id)}"
I'm guessing if you write something down in the changelog that there is a breaking change and explain why I'm assuming most people will understand 😛

2021-08-17 09:08 UTC, koying commented on custom_components/openrgb/light.py
> +            dev_unique_id = f"openrgb.{orgb_object_id(dev_id)}"
Updated

2021-08-17 13:21 UTC, FeikoJoosten approved these changes

2021-08-17 13:22 UTC, merged